import Head from 'next/head';
import React, { useEffect } from 'react';
import styles from '@/styles/Home.module.css';
import Scene from '@/components/Scene';
import { fetcher } from '@/utils/fetcher';
import Link from 'next/link';
import { useSession } from '@supabase/auth-helpers-react';

const Home = () => {
  const session = useSession();

  useEffect(() => {
    const callback = async () => {
      const videos = await fetcher('videos', 'list', {});
      console.log('videos :', videos);
    };

    callback();
  }, []);

  return (
    <>
      <Head>
        <title>3D Video Player App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Scene />
        <div
          className='container'
          style={{
            padding: '50px 0 100px 0',
            display: 'flex',
            justifyContent: 'center',
          }}
        >
          <Link href={session ? '/browse' : '/login'}>
            <button>Browse</button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
